// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// DEFENSIVE GUARD — without this, missing env vars (e.g. on a Lovable preview
// or any deploy without VITE_SUPABASE_URL set) cause createClient() to throw
// synchronously at module evaluation time. That uncaught exception KILLS the
// entire bundle: React never mounts, blank black screen, no console error.
//
// We log a clear warning and pass safe placeholder strings so module load
// succeeds. Any actual API call will fail gracefully (caught by the existing
// `if (error)` checks throughout the codebase) instead of crashing init.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.warn(
    '[supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY missing. ' +
    'The app will load but DB/auth/storage calls will fail. ' +
    'Set these env vars in your deployment (Lovable: Settings → Project Secrets).'
  );
}

export const supabase: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL || 'https://missing.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'missing-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
